namespace:
  name: sandbox

service:
  protocol: TCP
  port: 4111
  targetPort: 3111
  type: ClusterIP

image:
  repository: srishtiguleria/techtrends
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi

  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 3111

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz